import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { lusitana } from "@/components/ui/font";
import { Coins } from "lucide-react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html id="root" lang="pt-BR" className={`${lusitana} antialiased`}>
      <body className=" w-full">
        <header className="h-15 m-4 transition">
          <div className="h-full gap-3 rounded-xl border border-border-default p-4 items-end flex shrink-0 text-background">
            <Coins size="50" className="text-deep-navy" />
            <h1 className="text-display-large text-5xl font-light text-deep-navy leading-tight-large tracking-tight-large font-sohne">
              Finno
            </h1>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
