import "./globals.css";

import type { Metadata } from "next";
import { SourceCodePro } from "@/components/ui/font";
import { Coins } from "lucide-react";

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      id="root"
      lang="pt-BR"
      className={`${SourceCodePro.className} antialiased`}
    >
      <body className=" w-full">
        <header className="h-25 m-4 transition">
          <div className="h-full gap-3 rounded-xl border border-border-default p-4 items-end flex shrink-0 text-background">
            <Coins size="50" className="text-deep-navy" />
            <h1 className="text-display-large text-5xl font-light text-deep-navy leading-tight-large tracking-tight-large">
              Finno
            </h1>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
